[package]
name = "restmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.18"
erased-serde = "0.3.23"
serde = "1.0"
serde_derive = "1.0.144"
serde_yaml = "0.9"
typetag = "0.2.3"
